version: "3.9"
services:
  nodeserver:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: node
    image: mvdurao/node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node app.js
    networks:
      - laranet
   # volumes:
   #   - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laranet

  nginxserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: mvdurao/nginx
    networks:
      - laranet
    ports:
      - "8080:80"
    depends_on:
      - nodeserver

networks:
  laranet:
    driver: bridge